### ISSUE TITLE
Currently requires all of the project's PostCSS plugins to be installed globally... why?

### ISSUE THREAD

**Issue by crock** [soheilpro/mailwind#4]
I found out about this utility today on StackShare's daily email and instantly wanted to try it out! Got it all setup in my project and ran into some errors running it until I installed all of the PostCSS plugins my project was using globally.

```
yarn global add postcss autoprefixer
```

Note, I was running the `mailwind` command from a node.js script making a call to `child_process.execSync()`, so I could generate all the inlined email templates in one swoop, so I don't know if that makes a difference or not to whether the dependencies need to be installed globally.

**Comment by soheilpro** [comment]
Mailwind only requires Tailwind which is installed automatically as part of its dependencies. If you want to use it in your project, don't install it globally and you should be fine.

In the next version I'll change it to work as a library too, so you don't have to `exec` it.
